
"""
bbss - BBS Student Management

Default graphical user interface for bbss.

Main window was generated by calling:
    pyuic4 bbss_tabbed_gui.ui > main.py

Created on Mon Feb  23 15:08:56 2014

@author: Christian Wichmann
"""

import logging
from PyQt4 import QtGui
from PyQt4 import QtCore
from gui.main import Ui_BBSS_Main_Window


__all__ = ['start_gui']


logger = logging.getLogger('bbss.gui')


APP_NAME = "BBSS"


class Bbss_Gui(QtGui.QMainWindow, Ui_BBSS_Main_Window):
    """Main window for bbss"""

    def __init__(self, parent=None):
        """Initialize main window for bbss."""
        logger.info('Starting main window of bbss...')
        QtGui.QMainWindow.__init__(self, parent)
        # Set up the user interface from Designer.
        self.setupUi(self)
        #uic.loadUi('bbss_tabbed_gui.ui', self)
        self.set_signals_and_slots()

    def set_signals_and_slots(self):
        """Sets all signals and slots for main window."""
        self.import_data_button.clicked.connect(self.on_load_data)

    @QtCore.pyqtSlot()
    def on_load_data(self):
        logger.info('Loading data from file into gui...')


def start_gui():
    import sys

    app = QtGui.QApplication(sys.argv)
    app.setApplicationName(APP_NAME)

    main = Bbss_Gui()
    #main = uic.loadUi('bbss_tabbed_gui.ui')
    main.show()

    sys.exit(app.exec_())


if __name__ == "__main__":
    start_gui()
