# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/bbss_tabbed_gui.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BBSS_Main_Window(object):
    def setupUi(self, BBSS_Main_Window):
        BBSS_Main_Window.setObjectName("BBSS_Main_Window")
        BBSS_Main_Window.resize(658, 789)
        self.centralwidget = QtWidgets.QWidget(BBSS_Main_Window)
        self.centralwidget.setObjectName("centralwidget")
        self.TaskTabbedPane = QtWidgets.QTabWidget(self.centralwidget)
        self.TaskTabbedPane.setGeometry(QtCore.QRect(10, 10, 641, 731))
        self.TaskTabbedPane.setMinimumSize(QtCore.QSize(641, 451))
        self.TaskTabbedPane.setObjectName("TaskTabbedPane")
        self.import_tab = QtWidgets.QWidget()
        self.import_tab.setObjectName("import_tab")
        self.gridLayoutWidget = QtWidgets.QWidget(self.import_tab)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 611, 681))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.load_file_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.load_file_button.setObjectName("load_file_button")
        self.gridLayout.addWidget(self.load_file_button, 5, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 0, 1, 3)
        self.import_data_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.import_data_button.setObjectName("import_data_button")
        self.gridLayout.addWidget(self.import_data_button, 5, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.import_data_tableview = QtWidgets.QTableView(self.gridLayoutWidget)
        self.import_data_tableview.setObjectName("import_data_tableview")
        self.gridLayout.addWidget(self.import_data_tableview, 1, 0, 1, 3)
        self.delete_database_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.delete_database_button.setObjectName("delete_database_button")
        self.gridLayout.addWidget(self.delete_database_button, 5, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(10, 5, 10, 5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(52, 0))
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.import_filter_text = QtWidgets.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.import_filter_text.sizePolicy().hasHeightForWidth())
        self.import_filter_text.setSizePolicy(sizePolicy)
        self.import_filter_text.setMaxLength(50)
        self.import_filter_text.setObjectName("import_filter_text")
        self.horizontalLayout_2.addWidget(self.import_filter_text)
        self.search_result_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.search_result_label.setMinimumSize(QtCore.QSize(200, 0))
        self.search_result_label.setText("")
        self.search_result_label.setObjectName("search_result_label")
        self.horizontalLayout_2.addWidget(self.search_result_label)
        self.gridLayout.addLayout(self.horizontalLayout_2, 3, 0, 1, 3)
        self.TaskTabbedPane.addTab(self.import_tab, "")
        self.export_tab = QtWidgets.QWidget()
        self.export_tab.setObjectName("export_tab")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.export_tab)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 611, 683))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.gridLayoutWidget_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.added_student_table_label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.added_student_table_label.setObjectName("added_student_table_label")
        self.verticalLayout.addWidget(self.added_student_table_label)
        self.added_students_tableview = QtWidgets.QTableView(self.gridLayoutWidget_2)
        self.added_students_tableview.setMinimumSize(QtCore.QSize(0, 150))
        self.added_students_tableview.setObjectName("added_students_tableview")
        self.added_students_tableview.verticalHeader().setMinimumSectionSize(4)
        self.verticalLayout.addWidget(self.added_students_tableview)
        self.removed_student_table_label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.removed_student_table_label.setObjectName("removed_student_table_label")
        self.verticalLayout.addWidget(self.removed_student_table_label)
        self.removed_students_tableview = QtWidgets.QTableView(self.gridLayoutWidget_2)
        self.removed_students_tableview.setMinimumSize(QtCore.QSize(0, 150))
        self.removed_students_tableview.setObjectName("removed_students_tableview")
        self.verticalLayout.addWidget(self.removed_students_tableview)
        self.export_group = QtWidgets.QGroupBox(self.gridLayoutWidget_2)
        self.export_group.setMinimumSize(QtCore.QSize(0, 150))
        self.export_group.setObjectName("export_group")
        self.export_data_button = QtWidgets.QPushButton(self.export_group)
        self.export_data_button.setGeometry(QtCore.QRect(450, 90, 131, 31))
        self.export_data_button.setObjectName("export_data_button")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.export_group)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(310, 40, 273, 34))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.old_import_number = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.old_import_number.setMaxLength(3)
        self.old_import_number.setObjectName("old_import_number")
        self.horizontalLayout.addWidget(self.old_import_number, 0, QtCore.Qt.AlignHCenter)
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.new_import_number = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.new_import_number.setMaxLength(3)
        self.new_import_number.setObjectName("new_import_number")
        self.horizontalLayout.addWidget(self.new_import_number, 0, QtCore.Qt.AlignHCenter)
        self.export_format_combobox = QtWidgets.QComboBox(self.export_group)
        self.export_format_combobox.setGeometry(QtCore.QRect(120, 40, 161, 31))
        self.export_format_combobox.setObjectName("export_format_combobox")
        self.label_5 = QtWidgets.QLabel(self.export_group)
        self.label_5.setGeometry(QtCore.QRect(20, 50, 91, 16))
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.export_group)
        self.TaskTabbedPane.addTab(self.export_tab, "")
        self.search_tab = QtWidgets.QWidget()
        self.search_tab.setObjectName("search_tab")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.search_tab)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 611, 351))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.search_students_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.search_students_label.setObjectName("search_students_label")
        self.verticalLayout_3.addWidget(self.search_students_label)
        self.search_students_tableView = QtWidgets.QTableView(self.verticalLayoutWidget)
        self.search_students_tableView.setAlternatingRowColors(True)
        self.search_students_tableView.setObjectName("search_students_tableView")
        self.verticalLayout_3.addWidget(self.search_students_tableView)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(10, 5, 10, 5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        self.search_student_text = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.search_student_text.setObjectName("search_student_text")
        self.horizontalLayout_3.addWidget(self.search_student_text)
        self.clear_search_field_button = QtWidgets.QToolButton(self.verticalLayoutWidget)
        self.clear_search_field_button.setObjectName("clear_search_field_button")
        self.horizontalLayout_3.addWidget(self.clear_search_field_button)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.groupBox = QtWidgets.QGroupBox(self.search_tab)
        self.groupBox.setGeometry(QtCore.QRect(10, 370, 611, 311))
        self.groupBox.setObjectName("groupBox")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.groupBox)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(20, 30, 571, 270))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_2.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 0, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 4, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 2, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 3, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 5, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 6, 0, 1, 1)
        self.result_surname_text = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.result_surname_text.setReadOnly(True)
        self.result_surname_text.setObjectName("result_surname_text")
        self.gridLayout_2.addWidget(self.result_surname_text, 0, 1, 1, 1)
        self.result_name_text = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.result_name_text.setReadOnly(True)
        self.result_name_text.setObjectName("result_name_text")
        self.gridLayout_2.addWidget(self.result_name_text, 1, 1, 1, 1)
        self.result_class_text = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.result_class_text.setReadOnly(True)
        self.result_class_text.setObjectName("result_class_text")
        self.gridLayout_2.addWidget(self.result_class_text, 2, 1, 1, 1)
        self.result_birthday_text = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.result_birthday_text.setReadOnly(True)
        self.result_birthday_text.setObjectName("result_birthday_text")
        self.gridLayout_2.addWidget(self.result_birthday_text, 3, 1, 1, 1)
        self.result_username_text = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.result_username_text.setReadOnly(True)
        self.result_username_text.setObjectName("result_username_text")
        self.gridLayout_2.addWidget(self.result_username_text, 4, 1, 1, 1)
        self.result_password_text = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.result_password_text.setReadOnly(True)
        self.result_password_text.setObjectName("result_password_text")
        self.gridLayout_2.addWidget(self.result_password_text, 5, 1, 1, 1)
        self.result_imports_text = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.result_imports_text.setReadOnly(True)
        self.result_imports_text.setObjectName("result_imports_text")
        self.gridLayout_2.addWidget(self.result_imports_text, 6, 1, 1, 1)
        self.TaskTabbedPane.addTab(self.search_tab, "")
        self.options_tab = QtWidgets.QWidget()
        self.options_tab.setObjectName("options_tab")
        self.options_group = QtWidgets.QGroupBox(self.options_tab)
        self.options_group.setGeometry(QtCore.QRect(10, 10, 611, 221))
        self.options_group.setObjectName("options_group")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.options_group)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(20, 30, 571, 121))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.replace_classnames_checkbox = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.replace_classnames_checkbox.setChecked(True)
        self.replace_classnames_checkbox.setObjectName("replace_classnames_checkbox")
        self.verticalLayout_2.addWidget(self.replace_classnames_checkbox)
        self.replace_characters_checkbox = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.replace_characters_checkbox.setChecked(True)
        self.replace_characters_checkbox.setObjectName("replace_characters_checkbox")
        self.verticalLayout_2.addWidget(self.replace_characters_checkbox)
        self.store_in_db_checkbox = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.store_in_db_checkbox.setChecked(True)
        self.store_in_db_checkbox.setObjectName("store_in_db_checkbox")
        self.verticalLayout_2.addWidget(self.store_in_db_checkbox)
        self.settings_group = QtWidgets.QGroupBox(self.options_tab)
        self.settings_group.setGeometry(QtCore.QRect(10, 250, 611, 431))
        self.settings_group.setObjectName("settings_group")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.settings_group)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(20, 30, 571, 391))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_18 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_18.setFont(font)
        self.label_18.setTextFormat(QtCore.Qt.AutoText)
        self.label_18.setScaledContents(False)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_8.addWidget(self.label_18)
        self.label_19 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_19.setFont(font)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setWordWrap(True)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_8.addWidget(self.label_19)
        self.line_2 = QtWidgets.QFrame(self.verticalLayoutWidget_3)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_8.addWidget(self.line_2)
        self.label_20 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_20.setFont(font)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_8.addWidget(self.label_20)
        self.label_21 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_21.setFont(font)
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_8.addWidget(self.label_21)
        self.TaskTabbedPane.addTab(self.options_tab, "")
        BBSS_Main_Window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(BBSS_Main_Window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 658, 30))
        self.menubar.setObjectName("menubar")
        self.menuDatei = QtWidgets.QMenu(self.menubar)
        self.menuDatei.setObjectName("menuDatei")
        BBSS_Main_Window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(BBSS_Main_Window)
        self.statusbar.setObjectName("statusbar")
        BBSS_Main_Window.setStatusBar(self.statusbar)
        self.menu_exit = QtWidgets.QAction(BBSS_Main_Window)
        self.menu_exit.setObjectName("menu_exit")
        self.menu_delete_database = QtWidgets.QAction(BBSS_Main_Window)
        self.menu_delete_database.setObjectName("menu_delete_database")
        self.menu_delete_old_data = QtWidgets.QAction(BBSS_Main_Window)
        self.menu_delete_old_data.setObjectName("menu_delete_old_data")
        self.menuDatei.addAction(self.menu_delete_database)
        self.menuDatei.addAction(self.menu_delete_old_data)
        self.menuDatei.addSeparator()
        self.menuDatei.addAction(self.menu_exit)
        self.menubar.addAction(self.menuDatei.menuAction())
        self.label_8.setBuddy(self.import_data_tableview)
        self.label.setBuddy(self.import_filter_text)
        self.added_student_table_label.setBuddy(self.added_students_tableview)
        self.removed_student_table_label.setBuddy(self.removed_students_tableview)
        self.label_3.setBuddy(self.old_import_number)
        self.label_4.setBuddy(self.new_import_number)
        self.label_5.setBuddy(self.export_format_combobox)

        self.retranslateUi(BBSS_Main_Window)
        self.TaskTabbedPane.setCurrentIndex(2)
        self.menu_exit.triggered.connect(BBSS_Main_Window.close)
        QtCore.QMetaObject.connectSlotsByName(BBSS_Main_Window)

    def retranslateUi(self, BBSS_Main_Window):
        _translate = QtCore.QCoreApplication.translate
        BBSS_Main_Window.setWindowTitle(_translate("BBSS_Main_Window", "BBSS"))
        self.load_file_button.setText(_translate("BBSS_Main_Window", "Datei laden..."))
        self.label_8.setText(_translate("BBSS_Main_Window", "Importierte Schüler:"))
        self.import_data_button.setText(_translate("BBSS_Main_Window", "Daten importieren..."))
        self.delete_database_button.setText(_translate("BBSS_Main_Window", "Lösche Datenbank..."))
        self.label.setText(_translate("BBSS_Main_Window", "Suche:"))
        self.TaskTabbedPane.setTabText(self.TaskTabbedPane.indexOf(self.import_tab), _translate("BBSS_Main_Window", "Daten importieren"))
        self.added_student_table_label.setText(_translate("BBSS_Main_Window", "Hinzugefügte Schüler:"))
        self.removed_student_table_label.setText(_translate("BBSS_Main_Window", "Gelöschte Schüler:"))
        self.export_group.setTitle(_translate("BBSS_Main_Window", "Exportieren..."))
        self.export_data_button.setText(_translate("BBSS_Main_Window", "Daten exportieren..."))
        self.label_3.setText(_translate("BBSS_Main_Window", "von"))
        self.old_import_number.setText(_translate("BBSS_Main_Window", "0"))
        self.label_4.setText(_translate("BBSS_Main_Window", "bis"))
        self.new_import_number.setText(_translate("BBSS_Main_Window", "0"))
        self.label_5.setText(_translate("BBSS_Main_Window", "Exportformat:"))
        self.TaskTabbedPane.setTabText(self.TaskTabbedPane.indexOf(self.export_tab), _translate("BBSS_Main_Window", "Daten exportieren"))
        self.search_students_label.setText(_translate("BBSS_Main_Window", "Schüler suchen:"))
        self.label_6.setText(_translate("BBSS_Main_Window", "Suche: "))
        self.clear_search_field_button.setText(_translate("BBSS_Main_Window", "X"))
        self.groupBox.setTitle(_translate("BBSS_Main_Window", "Schülerinformationen"))
        self.label_2.setText(_translate("BBSS_Main_Window", "Vorname"))
        self.label_7.setText(_translate("BBSS_Main_Window", "Name"))
        self.label_11.setText(_translate("BBSS_Main_Window", "Benutzername"))
        self.label_9.setText(_translate("BBSS_Main_Window", "Klasse"))
        self.label_10.setText(_translate("BBSS_Main_Window", "Geburtsdatum"))
        self.label_12.setText(_translate("BBSS_Main_Window", "Passwort"))
        self.label_13.setText(_translate("BBSS_Main_Window", "Importe"))
        self.TaskTabbedPane.setTabText(self.TaskTabbedPane.indexOf(self.search_tab), _translate("BBSS_Main_Window", "Schüler suchen"))
        self.options_group.setTitle(_translate("BBSS_Main_Window", "Optionen"))
        self.replace_classnames_checkbox.setText(_translate("BBSS_Main_Window", "Klassennamen ersetzen"))
        self.replace_characters_checkbox.setText(_translate("BBSS_Main_Window", "Illegale Zeichen in Namen ersetzen"))
        self.store_in_db_checkbox.setText(_translate("BBSS_Main_Window", "Daten in Datenbank ablegen"))
        self.settings_group.setTitle(_translate("BBSS_Main_Window", "Über..."))
        self.label_18.setText(_translate("BBSS_Main_Window", "bbss - BBS Student Management"))
        self.label_19.setText(_translate("BBSS_Main_Window", "Software für das Erzeugen und Verwalten von Schülern und ihrer Benutzernamen und Passwörtern."))
        self.label_20.setText(_translate("BBSS_Main_Window", "Autor: Christian Wichmann"))
        self.label_21.setText(_translate("BBSS_Main_Window", "Lizensiert unter der GNU GPL v2 oder neuer."))
        self.TaskTabbedPane.setTabText(self.TaskTabbedPane.indexOf(self.options_tab), _translate("BBSS_Main_Window", "Optionen"))
        self.menuDatei.setTitle(_translate("BBSS_Main_Window", "Datei"))
        self.menu_exit.setText(_translate("BBSS_Main_Window", "Beenden"))
        self.menu_delete_database.setText(_translate("BBSS_Main_Window", "Datenbank löschen..."))
        self.menu_delete_old_data.setText(_translate("BBSS_Main_Window", "Alte Datensätze löschen..."))


