# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bbss_tabbed_gui.ui'
#
# Created: Thu Apr  3 07:56:20 2014
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_BBSS_Main_Window(object):
    def setupUi(self, BBSS_Main_Window):
        BBSS_Main_Window.setObjectName(_fromUtf8("BBSS_Main_Window"))
        BBSS_Main_Window.resize(658, 789)
        self.centralwidget = QtGui.QWidget(BBSS_Main_Window)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.TaskTabbedPane = QtGui.QTabWidget(self.centralwidget)
        self.TaskTabbedPane.setGeometry(QtCore.QRect(10, 10, 641, 731))
        self.TaskTabbedPane.setMinimumSize(QtCore.QSize(641, 451))
        self.TaskTabbedPane.setObjectName(_fromUtf8("TaskTabbedPane"))
        self.import_tab = QtGui.QWidget()
        self.import_tab.setObjectName(_fromUtf8("import_tab"))
        self.gridLayoutWidget = QtGui.QWidget(self.import_tab)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 611, 681))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.load_file_button = QtGui.QPushButton(self.gridLayoutWidget)
        self.load_file_button.setObjectName(_fromUtf8("load_file_button"))
        self.gridLayout.addWidget(self.load_file_button, 5, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_8 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 0, 0, 1, 3)
        self.import_data_button = QtGui.QPushButton(self.gridLayoutWidget)
        self.import_data_button.setObjectName(_fromUtf8("import_data_button"))
        self.gridLayout.addWidget(self.import_data_button, 5, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.import_data_tableview = QtGui.QTableView(self.gridLayoutWidget)
        self.import_data_tableview.setObjectName(_fromUtf8("import_data_tableview"))
        self.gridLayout.addWidget(self.import_data_tableview, 1, 0, 1, 3)
        self.delete_database_button = QtGui.QPushButton(self.gridLayoutWidget)
        self.delete_database_button.setObjectName(_fromUtf8("delete_database_button"))
        self.gridLayout.addWidget(self.delete_database_button, 5, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(10, 5, 10, 5)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(52, 0))
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        self.import_filter_text = QtGui.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.import_filter_text.sizePolicy().hasHeightForWidth())
        self.import_filter_text.setSizePolicy(sizePolicy)
        self.import_filter_text.setMaxLength(50)
        self.import_filter_text.setObjectName(_fromUtf8("import_filter_text"))
        self.horizontalLayout_2.addWidget(self.import_filter_text)
        self.search_result_label = QtGui.QLabel(self.gridLayoutWidget)
        self.search_result_label.setMinimumSize(QtCore.QSize(200, 0))
        self.search_result_label.setText(_fromUtf8(""))
        self.search_result_label.setObjectName(_fromUtf8("search_result_label"))
        self.horizontalLayout_2.addWidget(self.search_result_label)
        self.gridLayout.addLayout(self.horizontalLayout_2, 3, 0, 1, 3)
        self.TaskTabbedPane.addTab(self.import_tab, _fromUtf8(""))
        self.export_tab = QtGui.QWidget()
        self.export_tab.setObjectName(_fromUtf8("export_tab"))
        self.gridLayoutWidget_2 = QtGui.QWidget(self.export_tab)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 611, 683))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.gridLayoutWidget_2)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.added_student_table_label = QtGui.QLabel(self.gridLayoutWidget_2)
        self.added_student_table_label.setObjectName(_fromUtf8("added_student_table_label"))
        self.verticalLayout.addWidget(self.added_student_table_label)
        self.added_students_tableview = QtGui.QTableView(self.gridLayoutWidget_2)
        self.added_students_tableview.setMinimumSize(QtCore.QSize(0, 150))
        self.added_students_tableview.setObjectName(_fromUtf8("added_students_tableview"))
        self.added_students_tableview.verticalHeader().setMinimumSectionSize(4)
        self.verticalLayout.addWidget(self.added_students_tableview)
        self.removed_student_table_label = QtGui.QLabel(self.gridLayoutWidget_2)
        self.removed_student_table_label.setObjectName(_fromUtf8("removed_student_table_label"))
        self.verticalLayout.addWidget(self.removed_student_table_label)
        self.removed_students_tableview = QtGui.QTableView(self.gridLayoutWidget_2)
        self.removed_students_tableview.setMinimumSize(QtCore.QSize(0, 150))
        self.removed_students_tableview.setObjectName(_fromUtf8("removed_students_tableview"))
        self.verticalLayout.addWidget(self.removed_students_tableview)
        self.export_group = QtGui.QGroupBox(self.gridLayoutWidget_2)
        self.export_group.setMinimumSize(QtCore.QSize(0, 150))
        self.export_group.setObjectName(_fromUtf8("export_group"))
        self.export_data_button = QtGui.QPushButton(self.export_group)
        self.export_data_button.setGeometry(QtCore.QRect(470, 90, 121, 24))
        self.export_data_button.setObjectName(_fromUtf8("export_data_button"))
        self.horizontalLayoutWidget = QtGui.QWidget(self.export_group)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(310, 40, 273, 31))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_3 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout.addWidget(self.label_3)
        self.old_import_number = QtGui.QLineEdit(self.horizontalLayoutWidget)
        self.old_import_number.setMaxLength(3)
        self.old_import_number.setObjectName(_fromUtf8("old_import_number"))
        self.horizontalLayout.addWidget(self.old_import_number)
        self.label_4 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout.addWidget(self.label_4)
        self.new_import_number = QtGui.QLineEdit(self.horizontalLayoutWidget)
        self.new_import_number.setMaxLength(3)
        self.new_import_number.setObjectName(_fromUtf8("new_import_number"))
        self.horizontalLayout.addWidget(self.new_import_number)
        self.export_format_combobox = QtGui.QComboBox(self.export_group)
        self.export_format_combobox.setGeometry(QtCore.QRect(120, 40, 161, 31))
        self.export_format_combobox.setObjectName(_fromUtf8("export_format_combobox"))
        self.label_5 = QtGui.QLabel(self.export_group)
        self.label_5.setGeometry(QtCore.QRect(20, 50, 91, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout.addWidget(self.export_group)
        self.TaskTabbedPane.addTab(self.export_tab, _fromUtf8(""))
        self.options_tab = QtGui.QWidget()
        self.options_tab.setObjectName(_fromUtf8("options_tab"))
        self.options_group = QtGui.QGroupBox(self.options_tab)
        self.options_group.setGeometry(QtCore.QRect(10, 10, 611, 221))
        self.options_group.setObjectName(_fromUtf8("options_group"))
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.options_group)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(20, 30, 571, 161))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.replace_classnames_checkbox = QtGui.QCheckBox(self.verticalLayoutWidget_2)
        self.replace_classnames_checkbox.setChecked(True)
        self.replace_classnames_checkbox.setObjectName(_fromUtf8("replace_classnames_checkbox"))
        self.verticalLayout_2.addWidget(self.replace_classnames_checkbox)
        self.replace_characters_checkbox = QtGui.QCheckBox(self.verticalLayoutWidget_2)
        self.replace_characters_checkbox.setChecked(True)
        self.replace_characters_checkbox.setObjectName(_fromUtf8("replace_characters_checkbox"))
        self.verticalLayout_2.addWidget(self.replace_characters_checkbox)
        self.store_in_db_checkbox = QtGui.QCheckBox(self.verticalLayoutWidget_2)
        self.store_in_db_checkbox.setChecked(True)
        self.store_in_db_checkbox.setObjectName(_fromUtf8("store_in_db_checkbox"))
        self.verticalLayout_2.addWidget(self.store_in_db_checkbox)
        self.bonus_function_checkbox = QtGui.QCheckBox(self.verticalLayoutWidget_2)
        self.bonus_function_checkbox.setObjectName(_fromUtf8("bonus_function_checkbox"))
        self.verticalLayout_2.addWidget(self.bonus_function_checkbox)
        self.settings_group = QtGui.QGroupBox(self.options_tab)
        self.settings_group.setGeometry(QtCore.QRect(10, 250, 611, 171))
        self.settings_group.setObjectName(_fromUtf8("settings_group"))
        self.TaskTabbedPane.addTab(self.options_tab, _fromUtf8(""))
        BBSS_Main_Window.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(BBSS_Main_Window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 658, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuDatei = QtGui.QMenu(self.menubar)
        self.menuDatei.setObjectName(_fromUtf8("menuDatei"))
        BBSS_Main_Window.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(BBSS_Main_Window)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        BBSS_Main_Window.setStatusBar(self.statusbar)
        self.menu_exit = QtGui.QAction(BBSS_Main_Window)
        self.menu_exit.setObjectName(_fromUtf8("menu_exit"))
        self.menuDatei.addAction(self.menu_exit)
        self.menubar.addAction(self.menuDatei.menuAction())
        self.label_8.setBuddy(self.import_data_tableview)
        self.label.setBuddy(self.import_filter_text)
        self.added_student_table_label.setBuddy(self.added_students_tableview)
        self.removed_student_table_label.setBuddy(self.removed_students_tableview)
        self.label_3.setBuddy(self.old_import_number)
        self.label_4.setBuddy(self.new_import_number)
        self.label_5.setBuddy(self.export_format_combobox)

        self.retranslateUi(BBSS_Main_Window)
        self.TaskTabbedPane.setCurrentIndex(0)
        QtCore.QObject.connect(self.menu_exit, QtCore.SIGNAL(_fromUtf8("activated()")), BBSS_Main_Window.close)
        QtCore.QMetaObject.connectSlotsByName(BBSS_Main_Window)

    def retranslateUi(self, BBSS_Main_Window):
        BBSS_Main_Window.setWindowTitle(_translate("BBSS_Main_Window", "BBSS", None))
        self.load_file_button.setText(_translate("BBSS_Main_Window", "Datei laden...", None))
        self.label_8.setText(_translate("BBSS_Main_Window", "Importierte Schüler:", None))
        self.import_data_button.setText(_translate("BBSS_Main_Window", "Daten importieren...", None))
        self.delete_database_button.setText(_translate("BBSS_Main_Window", "Delete Database...", None))
        self.label.setText(_translate("BBSS_Main_Window", "Suche:", None))
        self.TaskTabbedPane.setTabText(self.TaskTabbedPane.indexOf(self.import_tab), _translate("BBSS_Main_Window", "Daten importieren", None))
        self.added_student_table_label.setText(_translate("BBSS_Main_Window", "Hinzugefügte Schüler:", None))
        self.removed_student_table_label.setText(_translate("BBSS_Main_Window", "Gelöschte Schüler:", None))
        self.export_group.setTitle(_translate("BBSS_Main_Window", "Exportieren...", None))
        self.export_data_button.setText(_translate("BBSS_Main_Window", "Daten exportieren...", None))
        self.label_3.setText(_translate("BBSS_Main_Window", "von", None))
        self.old_import_number.setText(_translate("BBSS_Main_Window", "0", None))
        self.label_4.setText(_translate("BBSS_Main_Window", "bis", None))
        self.new_import_number.setText(_translate("BBSS_Main_Window", "0", None))
        self.label_5.setText(_translate("BBSS_Main_Window", "Exportformat:", None))
        self.TaskTabbedPane.setTabText(self.TaskTabbedPane.indexOf(self.export_tab), _translate("BBSS_Main_Window", "Daten exportieren", None))
        self.options_group.setTitle(_translate("BBSS_Main_Window", "Optionen", None))
        self.replace_classnames_checkbox.setText(_translate("BBSS_Main_Window", "Klassennamen ersetzen", None))
        self.replace_characters_checkbox.setText(_translate("BBSS_Main_Window", "Illegale Zeichen in Namen ersetzen", None))
        self.store_in_db_checkbox.setText(_translate("BBSS_Main_Window", "Daten in Datenbank ablegen", None))
        self.bonus_function_checkbox.setText(_translate("BBSS_Main_Window", "Super-Duper-Funktion aktivieren", None))
        self.settings_group.setTitle(_translate("BBSS_Main_Window", "Weitere Einstellungen", None))
        self.TaskTabbedPane.setTabText(self.TaskTabbedPane.indexOf(self.options_tab), _translate("BBSS_Main_Window", "Optionen", None))
        self.menuDatei.setTitle(_translate("BBSS_Main_Window", "Datei", None))
        self.menu_exit.setText(_translate("BBSS_Main_Window", "Beenden", None))

